name: Compilación del Kernel - Samsung A04
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el código
        uses: actions/checkout@v4

      - name: Instalando herramientas
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip gcc-aarch64-linux-gnu clang lld libssl-dev

      - name: Bajando el Compilador (AOSP Clang)
        run: |
          # Clonamos el Clang oficial
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=1 -b master clang-aosp
          
          # Buscamos la carpeta exacta y la guardamos bien
          CLANG_BIN=$(ls -d $GITHUB_WORKSPACE/clang-aosp/clang-r*/bin)
          echo "$CLANG_BIN" >> $GITHUB_PATH

      - name: ¡Mandarle Mecha con build.sh!
        run: |
          # Ya no hace falta exportar el PATH porque lo hicimos arriba con GITHUB_PATH
          chmod +x "build (2).sh"
          
          ./"build (2).sh" kernel --jobs $(nproc --all) rsuntk-a04_defconfig
        env:
          KERNELSU: true
          IS_CI: true

      - name: Subiendo el Trofeo
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-SamsungA04-July
          path: "*.zip"
