name: Compilación del Kernel - Samsung A04
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el código del motor
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Instalando herramientas del taller
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip gcc-aarch64-linux-gnu clang libssl-dev

      - name: Bajando el Compilador (Proton Clang)
        run: |
          git clone https://github.com/kdrag0n/proton-clang.git --depth=1 clang

      - name: ¡Mandarle Mecha con build.sh!
        run: |
          # 1. Ponemos el compilador en el camino del sistema
          export PATH="$(pwd)/clang/bin:$PATH"
          
          # 2. Permisos para que el script labure
          chmod +x "build.sh"
          
          # 3. Arrancamos: target, jobs, config
          ./"build.sh" kernel --jobs $(nproc --all) rsuntk-a04_defconfig
        env:
          KERNELSU: true
          IS_CI: true # Le avisamos que es un servidor para que no pida confirmaciones

      - name: Subiendo el Trofeo (Kernel Zip)
        uses: actions/upload-artifact@v4 # ¡ESTE ES EL QUE IMPORTA, v4!
        with:
          name: Kernel-SamsungA04-July
          path: "*.zip" 
          compression-level: 0 # Para que no tarde mil años en comprimir lo que ya es un zip
